version: '3.8'
services:
  expo:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
